<center>
<img src="https://laelgelcpublic.s3.sa-east-1.amazonaws.com/lael_50_years_narrow_white.png.no_years.400px_96dpi.png" width="300" alt="LAEL 50 years logo">
<h3>APPLIED LINGUISTICS GRADUATE PROGRAMME (LAEL)</h3>
</center>
<hr>

# Corpus Linguistics - Study 1 - Phase 2 - Tatiana

## Load image source data 1

In [1]:
import pandas as pd

df_images_source_1 = pd.read_csv(
    "docs/text_uniq_first_with_photo_view.tsv",
    sep="\t"
)

,file,created_at,text_uniq,conversation_id,author_id,username,tweet_url,text,text_emojified,photo_uniq_id
0,file,created_at,tweet_00000001,conversation_id,author_id,username,tweet_url,text,text_emojified,file00000001.url
1,saude202003_n_00001.json,2020-03-30 23:58:27,tweet_00000006,convo_1244774019859206145,id_173533635,unknown,unknown,"Lembrando q estamos atendendo somente on-line,...","Lembrando q estamos atendendo somente on-line,...",saude202003_n_00001_00000001.jpg
2,saude202003_n_00001.json,2020-03-30 23:54:45,tweet_00000007,convo_1244774019859206145,id_173533635,unknown,unknown,"Não é muito, mas é a forma que encontramos par...","Não é muito, mas é a forma que encontramos par...",saude202003_n_00001_00000001.jpg
3,saude202003_n_00001.json,2020-03-30 23:50:57,tweet_00000022,convo_1244774142701981698,id_454396343,unknown,unknown,"Segundo levantamento da AFP (dados da OMS) 3,3...","Segundo levantamento da AFP (dados da OMS) 3,3...",saude202003_n_00001_00000002.jpg
4,saude202003_n_00002.json,2020-03-30 23:27:18,tweet_00000051,convo_1244693362361487364,id_191068627,sf79,https://twitter.com/sf79/status/12446933623614...,@cmelo @Francischini_ @jairbolsonaro A OMS nun...,@cmelo @Francischini_ @jairbolsonaro A OMS nun...,saude202003_n_00002_00000001.jpg

## Load image source data 2

In [3]:
import pandas as pd

df_images_source_2 = pd.read_csv(
    "docs/photos_url_view.tsv",
    sep="\t"
)

## Load image source data 3

In [5]:
import pandas as pd

df_images_source_3 = pd.read_csv(
    "docs/tati_oms/tati_scores_only.tsv",
    sep="\t"
)

## Filter tweets with image-source matches

In [9]:
df_tweets = df_images_source_1[
    df_images_source_1["text_uniq"].isin(df_images_source_3["file"])
].copy()

,file,created_at,text_uniq,conversation_id,author_id,username,tweet_url,text,text_emojified,photo_uniq_id
1,saude202003_n_00001.json,2020-03-30 23:58:27,tweet_00000006,convo_1244774019859206145,id_173533635,unknown,unknown,"Lembrando q estamos atendendo somente on-line,...","Lembrando q estamos atendendo somente on-line,...",saude202003_n_00001_00000001.jpg
2,saude202003_n_00001.json,2020-03-30 23:54:45,tweet_00000007,convo_1244774019859206145,id_173533635,unknown,unknown,"Não é muito, mas é a forma que encontramos par...","Não é muito, mas é a forma que encontramos par...",saude202003_n_00001_00000001.jpg
3,saude202003_n_00001.json,2020-03-30 23:50:57,tweet_00000022,convo_1244774142701981698,id_454396343,unknown,unknown,"Segundo levantamento da AFP (dados da OMS) 3,3...","Segundo levantamento da AFP (dados da OMS) 3,3...",saude202003_n_00001_00000002.jpg
4,saude202003_n_00002.json,2020-03-30 23:27:18,tweet_00000051,convo_1244693362361487364,id_191068627,sf79,https://twitter.com/sf79/status/12446933623614...,@cmelo @Francischini_ @jairbolsonaro A OMS nun...,@cmelo @Francischini_ @jairbolsonaro A OMS nun...,saude202003_n_00002_00000001.jpg
5,saude202003_n_00002.json,2020-03-30 23:26:49,tweet_00000054,convo_1244768070524166145,id_199501770,unknown,unknown,OMS diz que não há transmissão aérea de Covid-...,OMS diz que não há transmissão aérea de Covid-...,saude202003_n_00002_00000002.jpg

Drop the `text_emojified` column

In [11]:
df_tweets = df_tweets.drop(columns=["text_emojified"])

,file,created_at,text_uniq,conversation_id,author_id,username,tweet_url,text,photo_uniq_id
1,saude202003_n_00001.json,2020-03-30 23:58:27,tweet_00000006,convo_1244774019859206145,id_173533635,unknown,unknown,"Lembrando q estamos atendendo somente on-line,...",saude202003_n_00001_00000001.jpg
2,saude202003_n_00001.json,2020-03-30 23:54:45,tweet_00000007,convo_1244774019859206145,id_173533635,unknown,unknown,"Não é muito, mas é a forma que encontramos par...",saude202003_n_00001_00000001.jpg
3,saude202003_n_00001.json,2020-03-30 23:50:57,tweet_00000022,convo_1244774142701981698,id_454396343,unknown,unknown,"Segundo levantamento da AFP (dados da OMS) 3,3...",saude202003_n_00001_00000002.jpg
4,saude202003_n_00002.json,2020-03-30 23:27:18,tweet_00000051,convo_1244693362361487364,id_191068627,sf79,https://twitter.com/sf79/status/12446933623614...,@cmelo @Francischini_ @jairbolsonaro A OMS nun...,saude202003_n_00002_00000001.jpg
5,saude202003_n_00002.json,2020-03-30 23:26:49,tweet_00000054,convo_1244768070524166145,id_199501770,unknown,unknown,OMS diz que não há transmissão aérea de Covid-...,saude202003_n_00002_00000002.jpg

## Copy selected Tatiana images

In [15]:
from pathlib import Path
import shutil

source_dir = Path("corpus/cl_st1_ph2_tatiana_images_all")
target_dir = Path("corpus/cl_st1_ph2_tatiana_images")
target_dir.mkdir(parents=True, exist_ok=True)

photo_ids = (
    df_tweets["photo_uniq_id"]
    .dropna()
    .astype(str)
    .unique()
)

copied = 0
missing = []

for filename in photo_ids:
    src = source_dir / filename
    dst = target_dir / filename

    if src.exists():
        shutil.copy2(src, dst)
        copied += 1
    else:
        missing.append(filename)

print(f"Copied {copied} files to {target_dir}")
print(f"Missing {len(missing)} files")

if missing:
    print("First missing files:")
    print("\n".join(missing[:20]))

Copied 14450 files to corpus/cl_st1_ph2_tatiana_images
Missing 0 files

In [ ]:
df_tweets

## Export tweets dataset

In [16]:
from pathlib import Path

output_dir = Path("corpus")
output_dir.mkdir(parents=True, exist_ok=True)

df_tweets.to_json(output_dir / "tweets.ndjson", orient="records", lines=True, force_ascii=False)
df_tweets.to_csv(output_dir / "tweets.tsv", sep="\t", index=False)
df_tweets.to_excel(output_dir / "tweets.xlsx", index=False)

print(f"Exported {len(df_tweets):,} rows to:")
print(f"- {output_dir / 'tweets.ndjson'}")
print(f"- {output_dir / 'tweets.tsv'}")
print(f"- {output_dir / 'tweets.xlsx'}")

Exported 15,787 rows to:
- corpus/tweets.ndjson
- corpus/tweets.tsv
- corpus/tweets.xlsx