<center>
<img src="https://laelgelcpublic.s3.sa-east-1.amazonaws.com/lael_50_years_narrow_white.png.no_years.400px_96dpi.png" width="300" alt="LAEL 50 years logo">
<h3>APPLIED LINGUISTICS GRADUATE PROGRAMME (LAEL)</h3>
</center>
<hr>

# Corpus Linguistics - Study 1 - Phase 3 - Tatiana

This document aims to organise the tweet verbal and visual subcorpora data for Canonical Correlation Analysis (CCA).

## Tweet Verbal Subcorpus

Define the project name.

In [1]:
PROJECT = "cl_st1_ph2_tatiana"

In [2]:
from pathlib import Path

SCORES_FILE = Path(f"../{PROJECT}/docs/tati_oms/tati_scores_only.tsv")

### Load factor scores

In [3]:
import pandas as pd

scores_verbal_df = pd.read_csv(SCORES_FILE, sep="\t")
scores_verbal_df = scores_verbal_df.rename(columns={"file": "file_id"})

scores_verbal_df

               file_id  fac1  fac2  fac3  fac4  fac5  fac6
0       tweet_00000002    -2     1     0     0     0     0
1       tweet_00000003    -3     2     0     0     0     1
2       tweet_00000004     0     0    -1     0     0     0
3       tweet_00000005     0     0    -1     0     0     0
4       tweet_00000006     1     1     0    -1     0     0
...                ...   ...   ...   ...   ...   ...   ...
126863  tweet_00163249     0     0     0     0     0     0
126864  tweet_00163250     1     0     0     0     0     0
126865  tweet_00163251    -1     3     1    -1     0     0
126866  tweet_00163252     0     0     0     0     0     3
126867  tweet_00163253     0    -2     0     0     0     3

[126868 rows x 7 columns]

### Prepare verbal factor-score columns for CCA

Rename the verbal factor-score columns from `fac<n>` to `ver<n>` and keep only the file identifiers, decade metadata, and renamed verbal score columns needed for Canonical Correlation Analysis.

In [4]:
import re

verbal_factor_cols = [col for col in scores_verbal_df.columns if re.fullmatch(r"fac\d+", col)]
verbal_factor_cols = sorted(verbal_factor_cols, key=lambda col: int(col.replace("fac", "")))

verbal_rename_map = {
    col: col.replace("fac", "ver")
    for col in verbal_factor_cols
}

scores_verbal_df = scores_verbal_df.rename(columns=verbal_rename_map)

verbal_cols = [verbal_rename_map[col] for col in verbal_factor_cols]

scores_verbal_df = scores_verbal_df[
    ["file_id"] + verbal_cols
    ]

scores_verbal_df

               file_id  ver1  ver2  ver3  ver4  ver5  ver6
0       tweet_00000002    -2     1     0     0     0     0
1       tweet_00000003    -3     2     0     0     0     1
2       tweet_00000004     0     0    -1     0     0     0
3       tweet_00000005     0     0    -1     0     0     0
4       tweet_00000006     1     1     0    -1     0     0
...                ...   ...   ...   ...   ...   ...   ...
126863  tweet_00163249     0     0     0     0     0     0
126864  tweet_00163250     1     0     0     0     0     0
126865  tweet_00163251    -1     3     1    -1     0     0
126866  tweet_00163252     0     0     0     0     0     3
126867  tweet_00163253     0    -2     0     0     0     3

[126868 rows x 7 columns]

### Load tweets corpus

In [5]:
TWEETS_FILE = Path(f"../{PROJECT}/corpus/tweets.ndjson")

tweets_df = pd.read_json(TWEETS_FILE, lines=True)

tweets_df

,file,created_at,text_uniq,conversation_id,author_id,username,tweet_url,text,photo_uniq_id
0,saude202003_n_00001.json,2020-03-30 23:58:27,tweet_00000006,convo_1244774019859206145,id_173533635,unknown,unknown,"Lembrando q estamos atendendo somente on-line,...",saude202003_n_00001_00000001.jpg
1,saude202003_n_00001.json,2020-03-30 23:54:45,tweet_00000007,convo_1244774019859206145,id_173533635,unknown,unknown,"Não é muito, mas é a forma que encontramos par...",saude202003_n_00001_00000001.jpg
2,saude202003_n_00001.json,2020-03-30 23:50:57,tweet_00000022,convo_1244774142701981698,id_454396343,unknown,unknown,"Segundo levantamento da AFP (dados da OMS) 3,3...",saude202003_n_00001_00000002.jpg
3,saude202003_n_00002.json,2020-03-30 23:27:18,tweet_00000051,convo_1244693362361487364,id_191068627,sf79,https://twitter.com/sf79/status/12446933623614...,@cmelo @Francischini_ @jairbolsonaro A OMS nun...,saude202003_n_00002_00000001.jpg
4,saude202003_n_00002.json,2020-03-30 23:26:49,tweet_00000054,convo_1244768070524166145,id_199501770,unknown,unknown,OMS diz que não há transmissão aérea de Covid-...,saude202003_n_00002_00000002.jpg
...,...,...,...,...,...,...,...,...,...
15782,saude202303_n_00207.json,2023-03-06 23:52:37,tweet_00163212,convo_1632891969536966663,id_1485793803495641090,VascoN95,https://twitter.com/VascoN95/status/1632891969...,Neste guia atualizado em fevereiro de 2023 sob...,saude202303_n_00207_00000001.jpg
15783,saude202303_n_00207.json,2023-03-07 09:36:34,tweet_00163219,convo_1633038922753122305,id_1501277332119511048,chris_banida,https://twitter.com/chris_banida/status/163303...,Em breve esse venen☠️ virá para as crianças. h...,saude202303_n_00207_00000002.jpg
15784,saude202303_n_00207.json,2023-03-07 08:45:13,tweet_00163225,convo_1633026002245890049,id_2370633043,unknown,unknown,Aumenta a preocupação da OMS com a gripe aviár...,saude202303_n_00207_00000003.jpg
15785,saude202303_n_00207.json,2023-03-07 02:30:35,tweet_00163233,convo_1632931722000990210,id_1602447377771773953,anamanerolemos,https://twitter.com/anamanerolemos/status/1632...,A OMS muda seu plano de pandemia (que não menc...,saude202303_n_00207_00000004.png
15786,saude202303_n_00207.json,2023-03-06 23:39:34,tweet_00163250,convo_1632888684562268163,id_1153671708479512576,unknown,unknown,"Na recepção ao diretor da @anvisa_oficial, Dan...",saude202303_n_00207_00000005.jpg

### Add image IDs to verbal factor scores

In [6]:
image_id_map = tweets_df.set_index("text_uniq")["photo_uniq_id"]

scores_verbal_df.insert(
    loc=scores_verbal_df.columns.get_loc("file_id") + 1,
    column="image_id",
    value=scores_verbal_df["file_id"].map(image_id_map),
)

scores_verbal_df

,file_id,image_id,ver1,ver2,ver3,ver4,ver5,ver6
0,tweet_00000002,NaN,-2,1,0,0,0,0
1,tweet_00000003,NaN,-3,2,0,0,0,1
2,tweet_00000004,NaN,0,0,-1,0,0,0
3,tweet_00000005,NaN,0,0,-1,0,0,0
4,tweet_00000006,saude202003_n_00001_00000001.jpg,1,1,0,-1,0,0
...,...,...,...,...,...,...,...,...
126863,tweet_00163249,NaN,0,0,0,0,0,0
126864,tweet_00163250,saude202303_n_00207_00000005.jpg,1,0,0,0,0,0
126865,tweet_00163251,NaN,-1,3,1,-1,0,0
126866,tweet_00163252,NaN,0,0,0,0,0,3
126867,tweet_00163253,NaN,0,-2,0,0,0,3

## Tweet Visual Subcorpus

Define the project name.

In [7]:
PROJECT = "cl_st1_ph2_tatiana"

In [8]:
from pathlib import Path

SCORES_FILE = Path(f"../{PROJECT}/sas/output_{PROJECT}/{PROJECT}_scores_only.tsv")
FILE_IDS_PATH = Path(f"../{PROJECT}/file_ids.txt")

### Load factor scores

In [9]:
import pandas as pd

scores_visual_df = pd.read_csv(SCORES_FILE, sep="\t")
scores_visual_df = scores_visual_df.rename(columns={"filename": "text_id"})

scores_visual_df

       text_id  fac1  fac2  fac3  fac4  fac5  fac6  fac7
0      t000001     0     0     0     0     0     0    -2
1      t000002     1     0     0     1     0     0    -2
2      t000003     6     0     0     0     0     0    -6
3      t000004     1     0     0     1     0     0    -3
4      t000005    19    -1     0     1     0     1     0
...        ...   ...   ...   ...   ...   ...   ...   ...
11844  t011865     0     0     0     0     0     0    -4
11845  t011866     3     0     0     0     0     0    -4
11846  t011867     0     0     0     0     0    -5     0
11847  t011868     0     8     0     4     0     0    19
11848  t011869     0     0     0     0     0     1     0

[11849 rows x 8 columns]

### Load file ID mapping

In [10]:
file_ids_visual_df = pd.read_csv(
    FILE_IDS_PATH,
    sep=" ",
    names=["text_id", "filename"],
)

file_ids_visual_df.head()

   text_id                          filename
0  t000001  saude202003_n_00001_00000001.txt
1  t000002  saude202003_n_00001_00000002.txt
2  t000003  saude202003_n_00002_00000001.txt
3  t000004  saude202003_n_00002_00000002.txt
4  t000005  saude202003_n_00002_00000003.txt

### Merge factor scores with file ID mapping

In [11]:
scores_file_ids_visual_df = scores_visual_df.merge(file_ids_visual_df, on="text_id", how="left")
scores_file_ids_visual_df = scores_file_ids_visual_df[
    ["text_id", "filename"]
    + [col for col in scores_file_ids_visual_df.columns if col not in ["text_id", "filename"]]
    ]

scores_file_ids_visual_df

,text_id,filename,fac1,fac2,fac3,fac4,fac5,fac6,fac7
0,t000001,saude202003_n_00001_00000001.txt,0,0,0,0,0,0,-2
1,t000002,saude202003_n_00001_00000002.txt,1,0,0,1,0,0,-2
2,t000003,saude202003_n_00002_00000001.txt,6,0,0,0,0,0,-6
3,t000004,saude202003_n_00002_00000002.txt,1,0,0,1,0,0,-3
4,t000005,saude202003_n_00002_00000003.txt,19,-1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...
11844,t011865,saude202303_n_00207_00000001.txt,0,0,0,0,0,0,-4
11845,t011866,saude202303_n_00207_00000002.txt,3,0,0,0,0,0,-4
11846,t011867,saude202303_n_00207_00000003.txt,0,0,0,0,0,-5,0
11847,t011868,saude202303_n_00207_00000004.txt,0,8,0,4,0,0,19
11848,t011869,saude202303_n_00207_00000005.txt,0,0,0,0,0,1,0

### Prepare visual factor-score columns for CCA

Rename the visual factor-score columns from `fac<n>` to `vis<n>` and keep only the file identifiers, decade metadata, and renamed visual score columns needed for Canonical Correlation Analysis.

In [12]:
import re

verbal_factor_cols = [col for col in scores_file_ids_visual_df.columns if re.fullmatch(r"fac\d+", col)]
verbal_factor_cols = sorted(verbal_factor_cols, key=lambda col: int(col.replace("fac", "")))

verbal_rename_map = {
    col: col.replace("fac", "vis")
    for col in verbal_factor_cols
}

scores_file_ids_visual_df = scores_file_ids_visual_df.rename(columns=verbal_rename_map)

verbal_cols = [verbal_rename_map[col] for col in verbal_factor_cols]

scores_file_ids_visual_df = scores_file_ids_visual_df[
    ["text_id", "filename"] + verbal_cols
    ]

scores_file_ids_visual_df

,text_id,filename,vis1,vis2,vis3,vis4,vis5,vis6,vis7
0,t000001,saude202003_n_00001_00000001.txt,0,0,0,0,0,0,-2
1,t000002,saude202003_n_00001_00000002.txt,1,0,0,1,0,0,-2
2,t000003,saude202003_n_00002_00000001.txt,6,0,0,0,0,0,-6
3,t000004,saude202003_n_00002_00000002.txt,1,0,0,1,0,0,-3
4,t000005,saude202003_n_00002_00000003.txt,19,-1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...
11844,t011865,saude202303_n_00207_00000001.txt,0,0,0,0,0,0,-4
11845,t011866,saude202303_n_00207_00000002.txt,3,0,0,0,0,0,-4
11846,t011867,saude202303_n_00207_00000003.txt,0,0,0,0,0,-5,0
11847,t011868,saude202303_n_00207_00000004.txt,0,8,0,4,0,0,19
11848,t011869,saude202303_n_00207_00000005.txt,0,0,0,0,0,1,0

### Add verbal file IDs to visual scores

In [13]:
visual_to_verbal_file_id_map = (
    scores_verbal_df
    .dropna(subset=["image_id"])
    .assign(image_stem=lambda df: df["image_id"].map(lambda value: Path(value).stem))
    .drop_duplicates(subset="image_stem")
    .set_index("image_stem")["file_id"]
)

visual_filename_stems = scores_file_ids_visual_df["filename"].map(lambda value: Path(value).stem)

scores_file_ids_visual_df.insert(
    loc=scores_file_ids_visual_df.columns.get_loc("text_id") + 1,
    column="file_id",
    value=visual_filename_stems.map(visual_to_verbal_file_id_map),
)

scores_file_ids_visual_df

,text_id,file_id,filename,vis1,vis2,vis3,vis4,vis5,vis6,vis7
0,t000001,tweet_00000006,saude202003_n_00001_00000001.txt,0,0,0,0,0,0,-2
1,t000002,tweet_00000022,saude202003_n_00001_00000002.txt,1,0,0,1,0,0,-2
2,t000003,tweet_00000051,saude202003_n_00002_00000001.txt,6,0,0,0,0,0,-6
3,t000004,tweet_00000054,saude202003_n_00002_00000002.txt,1,0,0,1,0,0,-3
4,t000005,tweet_00000073,saude202003_n_00002_00000003.txt,19,-1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...
11844,t011865,tweet_00163212,saude202303_n_00207_00000001.txt,0,0,0,0,0,0,-4
11845,t011866,tweet_00163219,saude202303_n_00207_00000002.txt,3,0,0,0,0,0,-4
11846,t011867,tweet_00163225,saude202303_n_00207_00000003.txt,0,0,0,0,0,-5,0
11847,t011868,tweet_00163233,saude202303_n_00207_00000004.txt,0,8,0,4,0,0,19
11848,t011869,tweet_00163250,saude202303_n_00207_00000005.txt,0,0,0,0,0,1,0

## Identify misalignment between visual and verbal dimension score DataFrames

In [14]:
verbal_file_ids = set(scores_verbal_df["file_id"])
visual_file_ids = set(scores_file_ids_visual_df["file_id"])

file_id_diff = {
    "only_in_verbal": sorted(verbal_file_ids - visual_file_ids),
    "only_in_visual": sorted(visual_file_ids - verbal_file_ids),
    "n_only_in_verbal": len(verbal_file_ids - visual_file_ids),
    "n_only_in_visual": len(visual_file_ids - verbal_file_ids),
    "n_in_both": len(verbal_file_ids & visual_file_ids),
    "n_verbal": len(verbal_file_ids),
    "n_visual": len(visual_file_ids),
}

display(file_id_diff)

{'only_in_verbal': ['tweet_00000002',
  'tweet_00000003',
  'tweet_00000004',
  'tweet_00000005',
  'tweet_00000007',
  'tweet_00000008',
  'tweet_00000009',
  'tweet_00000010',
  'tweet_00000011',
  'tweet_00000015',
  'tweet_00000016',
  'tweet_00000017',
  'tweet_00000018',
  'tweet_00000019',
  'tweet_00000020',
  'tweet_00000021',
  'tweet_00000023',
  'tweet_00000024',
  'tweet_00000025',
  'tweet_00000026',
  'tweet_00000027',
  'tweet_00000030',
  'tweet_00000031',
  'tweet_00000032',
  'tweet_00000033',
  'tweet_00000034',
  'tweet_00000035',
  'tweet_00000037',
  'tweet_00000038',
  'tweet_00000039',
  'tweet_00000040',
  'tweet_00000041',
  'tweet_00000042',
  'tweet_00000043',
  'tweet_00000044',
  'tweet_00000045',
  'tweet_00000046',
  'tweet_00000047',
  'tweet_00000048',
  'tweet_00000049',
  'tweet_00000050',
  'tweet_00000052',
  'tweet_00000053',
  'tweet_00000055',
  'tweet_00000056',
  'tweet_00000057',
  'tweet_00000058',
  'tweet_00000059',
  'tweet_00000060',
  'tweet_00000061',
  'tweet_00000062',
  'tweet_00000064',
  'tweet_00000065',
  'tweet_00000066',
  'tweet_00000067',
  'tweet_00000068',
  'tweet_00000069',
  'tweet_00000070',
  'tweet_00000071',
  'tweet_00000072',
  'tweet_00000074',
  'tweet_00000075',
  'tweet_00000077',
  'tweet_00000078',
  'tweet_00000080',
  'tweet_00000081',
  'tweet_00000082',
  'tweet_00000083',
  'tweet_00000084',
  'tweet_00000086',
  'tweet_00000087',
  'tweet_00000088',
  'tweet_00000089',
  'tweet_00000090',
  'tweet_00000091',
  'tweet_00000092',
  'tweet_00000094',
  'tweet_00000095',
  'tweet_00000096',
  'tweet_00000097',
  'tweet_00000098',
  'tweet_00000099',
  'tweet_00000101',
  'tweet_00000102',
  'tweet_00000103',
  'tweet_00000104',
  'tweet_00000105',
  'tweet_00000106',
  'tweet_00000107',
  'tweet_00000109',
  'tweet_00000110',
  'tweet_00000113',
  'tweet_00000115',
  'tweet_00000116',
  'tweet_00000117',
  'tweet_00000118',
  'tweet_00000120',
  'tweet_00000121',
  'tweet_00000122',
  'tweet_00000124',
  'tweet_00000125',
  'tweet_00000126',
  'tweet_00000129',
  'tweet_00000130',
  'tweet_00000133',
  'tweet_00000134',
  'tweet_00000135',
  'tweet_00000136',
  'tweet_00000137',
  'tweet_00000138',
  'tweet_00000139',
  'tweet_00000140',
  'tweet_00000141',
  'tweet_00000142',
  'tweet_00000143',
  'tweet_00000144',
  'tweet_00000145',
  'tweet_00000146',
  'tweet_00000148',
  'tweet_00000150',
  'tweet_00000151',
  'tweet_00000152',
  'tweet_00000153',
  'tweet_00000154',
  'tweet_00000155',
  'tweet_00000156',
  'tweet_00000157',
  'tweet_00000158',
  'tweet_00000159',
  'tweet_00000160',
  'tweet_00000162',
  'tweet_00000164',
  'tweet_00000165',
  'tweet_00000167',
  'tweet_00000168',
  'tweet_00000170',
  'tweet_00000171',
  'tweet_00000172',
  'tweet_00000173',
  'tweet_00000174',
  'tweet_00000176',
  'tweet_00000177',
  'tweet_00000178',
  'tweet_00000179',
  'tweet_00000180',
  'tweet_00000181',
  'tweet_00000182',
  'tweet_00000183',
  'tweet_00000184',
  'tweet_00000185',
  'tweet_00000186',
  'tweet_00000187',
  'tweet_00000189',
  'tweet_00000190',
  'tweet_00000191',
  'tweet_00000192',
  'tweet_00000193',
  'tweet_00000195',
  'tweet_00000196',
  'tweet_00000198',
  'tweet_00000199',
  'tweet_00000200',
  'tweet_00000202',
  'tweet_00000203',
  'tweet_00000204',
  'tweet_00000205',
  'tweet_00000207',
  'tweet_00000208',
  'tweet_00000209',
  'tweet_00000210',
  'tweet_00000211',
  'tweet_00000213',
  'tweet_00000214',
  'tweet_00000215',
  'tweet_00000217',
  'tweet_00000219',
  'tweet_00000220',
  'tweet_00000221',
  'tweet_00000222',
  'tweet_00000223',
  'tweet_00000225',
  'tweet_00000226',
  'tweet_00000227',
  'tweet_00000228',
  'tweet_00000229',
  'tweet_00000230',
  'tweet_00000231',
  'tweet_00000232',
  'tweet_00000233',
  'tweet_00000234',
  'tweet_00000235',
  'tweet_00000236',
  'tweet_00000237',
  'tweet_00000238',
  'tweet_00000239',
  'tweet_00000240',
  'tweet_00000241',
  'tweet_00000243',
  'tweet_00000244',
  'tweet_00000245',
  'tweet_00000246',
  'tweet_00000248',
  'tweet_00000249',
  'tweet_00000250',
  'tweet_00000251',
  'tweet_00000252',
  'tweet_00000253',
  'tweet_00000254',
  'tweet_00000255',
  'tweet_00000256',
  'tweet_00000257',
  'tweet_00000258',
  'tweet_00000259',
  'tweet_00000261',
  'tweet_00000263',
  'tweet_00000265',
  'tweet_00000267',
  'tweet_00000268',
  'tweet_00000270',
  'tweet_00000272',
  'tweet_00000274',
  'tweet_00000275',
  'tweet_00000277',
  'tweet_00000278',
  'tweet_00000279',
  'tweet_00000282',
  'tweet_00000283',
  'tweet_00000284',
  'tweet_00000285',
  'tweet_00000286',
  'tweet_00000287',
  'tweet_00000290',
  'tweet_00000291',
  'tweet_00000292',
  'tweet_00000293',
  'tweet_00000294',
  'tweet_00000295',
  'tweet_00000296',
  'tweet_00000297',
  'tweet_00000298',
  'tweet_00000300',
  'tweet_00000301',
  'tweet_00000303',
  'tweet_00000304',
  'tweet_00000305',
  'tweet_00000306',
  'tweet_00000307',
  'tweet_00000308',
  'tweet_00000309',
  'tweet_00000310',
  'tweet_00000311',
  'tweet_00000312',
  'tweet_00000313',
  'tweet_00000316',
  'tweet_00000317',
  'tweet_00000319',
  'tweet_00000320',
  'tweet_00000321',
  'tweet_00000322',
  'tweet_00000323',
  'tweet_00000324',
  'tweet_00000325',
  'tweet_00000326',
  'tweet_00000331',
  'tweet_00000332',
  'tweet_00000333',
  'tweet_00000334',
  'tweet_00000335',
  'tweet_00000336',
  'tweet_00000337',
  'tweet_00000338',
  'tweet_00000341',
  'tweet_00000342',
  'tweet_00000344',
  'tweet_00000345',
  'tweet_00000347',
  'tweet_00000348',
  'tweet_00000349',
  'tweet_00000350',
  'tweet_00000351',
  'tweet_00000352',
  'tweet_00000353',
  'tweet_00000355',
  'tweet_00000356',
  'tweet_00000357',
  'tweet_00000358',
  'tweet_00000359',
  'tweet_00000360',
  'tweet_00000361',
  'tweet_00000362',
  'tweet_00000364',
  'tweet_00000365',
  'tweet_00000366',
  'tweet_00000367',
  'tweet_00000368',
  'tweet_00000369',
  'tweet_00000370',
  'tweet_00000371',
  'tweet_00000372',
  'tweet_00000374',
  'tweet_00000375',
  'tweet_00000377',
  'tweet_00000378',
  'tweet_00000379',
  'tweet_00000380',
  'tweet_00000381',
  'tweet_00000383',
  'tweet_00000384',
  'tweet_00000385',
  'tweet_00000386',
  'tweet_00000389',
  'tweet_00000390',
  'tweet_00000392',
  'tweet_00000393',
  'tweet_00000394',
  'tweet_00000395',
  'tweet_00000396',
  'tweet_00000397',
  'tweet_00000398',
  'tweet_00000399',
  'tweet_00000400',
  'tweet_00000401',
  'tweet_00000402',
  'tweet_00000403',
  'tweet_00000404',
  'tweet_00000406',
  'tweet_00000408',
  'tweet_00000410',
  'tweet_00000412',
  'tweet_00000414',
  'tweet_00000416',
  'tweet_00000417',
  'tweet_00000419',
  'tweet_00000420',
  'tweet_00000421',
  'tweet_00000422',
  'tweet_00000425',
  'tweet_00000426',
  'tweet_00000427',
  'tweet_00000429',
  'tweet_00000430',
  'tweet_00000431',
  'tweet_00000433',
  'tweet_00000434',
  'tweet_00000435',
  'tweet_00000437',
  'tweet_00000438',
  'tweet_00000439',
  'tweet_00000440',
  'tweet_00000444',
  'tweet_00000445',
  'tweet_00000446',
  'tweet_00000447',
  'tweet_00000448',
  'tweet_00000449',
  'tweet_00000450',
  'tweet_00000451',
  'tweet_00000452',
  'tweet_00000453',
  'tweet_00000454',
  'tweet_00000455',
  'tweet_00000456',
  'tweet_00000457',
  'tweet_00000458',
  'tweet_00000460',
  'tweet_00000461',
  'tweet_00000462',
  'tweet_00000463',
  'tweet_00000465',
  'tweet_00000467',
  'tweet_00000468',
  'tweet_00000469',
  'tweet_00000470',
  'tweet_00000472',
  'tweet_00000473',
  'tweet_00000474',
  'tweet_00000476',
  'tweet_00000477',
  'tweet_00000478',
  'tweet_00000479',
  'tweet_00000480',
  'tweet_00000481',
  'tweet_00000483',
  'tweet_00000484',
  'tweet_00000485',
  'tweet_00000486',
  'tweet_00000487',
  'tweet_00000488',
  'tweet_00000489',
  'tweet_00000490',
  'tweet_00000491',
  'tweet_00000493',
  'tweet_00000494',
  'tweet_00000496',
  'tweet_00000497',
  'tweet_00000498',
  'tweet_00000501',
  'tweet_00000502',
  'tweet_00000504',
  'tweet_00000505',
  'tweet_00000508',
  'tweet_00000509',
  'tweet_00000510',
  'tweet_00000511',
  'tweet_00000512',
  'tweet_00000513',
  'tweet_00000514',
  'tweet_00000515',
  'tweet_00000516',
  'tweet_00000517',
  'tweet_00000518',
  'tweet_00000519',
  'tweet_00000520',
  'tweet_00000523',
  'tweet_00000524',
  'tweet_00000525',
  'tweet_00000526',
  'tweet_00000527',
  'tweet_00000528',
  'tweet_00000529',
  'tweet_00000530',
  'tweet_00000531',
  'tweet_00000532',
  'tweet_00000533',
  'tweet_00000534',
  'tweet_00000535',
  'tweet_00000536',
  'tweet_00000537',
  'tweet_00000538',
  'tweet_00000540',
  'tweet_00000542',
  'tweet_00000543',
  'tweet_00000544',
  'tweet_00000545',
  'tweet_00000546',
  'tweet_00000547',
  'tweet_00000548',
  'tweet_00000551',
  'tweet_00000552',
  'tweet_00000553',
  'tweet_00000554',
  'tweet_00000555',
  'tweet_00000556',
  'tweet_00000557',
  'tweet_00000558',
  'tweet_00000559',
  'tweet_00000560',
  'tweet_00000562',
  'tweet_00000563',
  'tweet_00000565',
  'tweet_00000567',
  'tweet_00000568',
  'tweet_00000569',
  'tweet_00000570',
  'tweet_00000571',
  'tweet_00000572',
  'tweet_00000573',
  'tweet_00000575',
  'tweet_00000576',
  'tweet_00000577',
  'tweet_00000578',
  'tweet_00000580',
  'tweet_00000581',
  'tweet_00000582',
  'tweet_00000584',
  'tweet_00000585',
  'tweet_00000587',
  'tweet_00000589',
  'tweet_00000590',
  'tweet_00000591',
  'tweet_00000592',
  'tweet_00000593',
  'tweet_00000594',
  'tweet_00000596',
  'tweet_00000597',
  'tweet_00000598',
  'tweet_00000599',
  'tweet_00000600',
  'tweet_00000602',
  'tweet_00000603',
  'tweet_00000606',
  'tweet_00000607',
  'tweet_00000608',
  'tweet_00000609',
  'tweet_00000610',
  'tweet_00000611',
  'tweet_00000614',
  'tweet_00000615',
  'tweet_00000616',
  'tweet_00000620',
  'tweet_00000621',
  'tweet_00000623',
  'tweet_00000624',
  'tweet_00000627',
  'tweet_00000628',
  'tweet_00000629',
  'tweet_00000631',
  'tweet_00000633',
  'tweet_00000634',
  'tweet_00000637',
  'tweet_00000639',
  'tweet_00000640',
  'tweet_00000642',
  'tweet_00000643',
  'tweet_00000644',
  'tweet_00000645',
  'tweet_00000646',
  'tweet_00000647',
  'tweet_00000648',
  'tweet_00000649',
  'tweet_00000650',
  'tweet_00000651',
  'tweet_00000652',
  'tweet_00000653',
  'tweet_00000654',
  'tweet_00000655',
  'tweet_00000656',
  'tweet_00000658',
  'tweet_00000659',
  'tweet_00000660',
  'tweet_00000661',
  'tweet_00000662',
  'tweet_00000663',
  'tweet_00000665',
  'tweet_00000666',
  'tweet_00000668',
  'tweet_00000669',
  'tweet_00000670',
  'tweet_00000671',
  'tweet_00000673',
  'tweet_00000674',
  'tweet_00000675',
  'tweet_00000676',
  'tweet_00000677',
  'tweet_00000678',
  'tweet_00000679',
  'tweet_00000680',
  'tweet_00000681',
  'tweet_00000682',
  'tweet_00000683',
  'tweet_00000684',
  'tweet_00000685',
  'tweet_00000686',
  'tweet_00000687',
  'tweet_00000689',
  'tweet_00000691',
  'tweet_00000692',
  'tweet_00000693',
  'tweet_00000694',
  'tweet_00000695',
  'tweet_00000697',
  'tweet_00000698',
  'tweet_00000699',
  'tweet_00000700',
  'tweet_00000701',
  'tweet_00000702',
  'tweet_00000703',
  'tweet_00000705',
  'tweet_00000708',
  'tweet_00000711',
  'tweet_00000713',
  'tweet_00000714',
  'tweet_00000716',
  'tweet_00000717',
  'tweet_00000718',
  'tweet_00000719',
  'tweet_00000722',
  'tweet_00000724',
  'tweet_00000725',
  'tweet_00000726',
  'tweet_00000727',
  'tweet_00000728',
  'tweet_00000729',
  'tweet_00000730',
  'tweet_00000731',
  'tweet_00000732',
  'tweet_00000734',
  'tweet_00000736',
  'tweet_00000737',
  'tweet_00000738',
  'tweet_00000739',
  'tweet_00000740',
  'tweet_00000741',
  'tweet_00000742',
  'tweet_00000745',
  'tweet_00000746',
  'tweet_00000747',
  'tweet_00000749',
  'tweet_00000750',
  'tweet_00000751',
  'tweet_00000752',
  'tweet_00000753',
  'tweet_00000754',
  'tweet_00000755',
  'tweet_00000756',
  'tweet_00000757',
  'tweet_00000758',
  'tweet_00000759',
  'tweet_00000760',
  'tweet_00000761',
  'tweet_00000763',
  'tweet_00000764',
  'tweet_00000765',
  'tweet_00000766',
  'tweet_00000767',
  'tweet_00000768',
  'tweet_00000770',
  'tweet_00000771',
  'tweet_00000773',
  'tweet_00000774',
  'tweet_00000775',
  'tweet_00000776',
  'tweet_00000778',
  'tweet_00000779',
  'tweet_00000780',
  'tweet_00000781',
  'tweet_00000782',
  'tweet_00000783',
  'tweet_00000784',
  'tweet_00000785',
  'tweet_00000786',
  'tweet_00000790',
  'tweet_00000794',
  'tweet_00000797',
  'tweet_00000798',
  'tweet_00000799',
  'tweet_00000800',
  'tweet_00000801',
  'tweet_00000802',
  'tweet_00000803',
  'tweet_00000804',
  'tweet_00000805',
  'tweet_00000807',
  'tweet_00000808',
  'tweet_00000809',
  'tweet_00000810',
  'tweet_00000811',
  'tweet_00000812',
  'tweet_00000814',
  'tweet_00000817',
  'tweet_00000818',
  'tweet_00000819',
  'tweet_00000821',
  'tweet_00000822',
  'tweet_00000823',
  'tweet_00000824',
  'tweet_00000825',
  'tweet_00000828',
  'tweet_00000829',
  'tweet_00000830',
  'tweet_00000832',
  'tweet_00000833',
  'tweet_00000834',
  'tweet_00000835',
  'tweet_00000836',
  'tweet_00000837',
  'tweet_00000840',
  'tweet_00000841',
  'tweet_00000843',
  'tweet_00000845',
  'tweet_00000847',
  'tweet_00000849',
  'tweet_00000853',
  'tweet_00000854',
  'tweet_00000855',
  'tweet_00000856',
  'tweet_00000857',
  'tweet_00000858',
  'tweet_00000859',
  'tweet_00000860',
  'tweet_00000861',
  'tweet_00000862',
  'tweet_00000863',
  'tweet_00000864',
  'tweet_00000865',
  'tweet_00000868',
  'tweet_00000870',
  'tweet_00000871',
  'tweet_00000872',
  'tweet_00000873',
  'tweet_00000874',
  'tweet_00000875',
  'tweet_00000876',
  'tweet_00000877',
  'tweet_00000880',
  'tweet_00000882',
  'tweet_00000883',
  'tweet_00000884',
  'tweet_00000885',
  'tweet_00000886',
  'tweet_00000887',
  'tweet_00000888',
  'tweet_00000890',
  'tweet_00000891',
  'tweet_00000893',
  'tweet_00000894',
  'tweet_00000896',
  'tweet_00000897',
  'tweet_00000898',
  'tweet_00000901',
  'tweet_00000902',
  'tweet_00000905',
  'tweet_00000906',
  'tweet_00000908',
  'tweet_00000910',
  'tweet_00000911',
  'tweet_00000912',
  'tweet_00000913',
  'tweet_00000914',
  'tweet_00000915',
  'tweet_00000918',
  'tweet_00000919',
  'tweet_00000920',
  'tweet_00000921',
  'tweet_00000922',
  'tweet_00000923',
  'tweet_00000924',
  'tweet_00000925',
  'tweet_00000926',
  'tweet_00000927',
  'tweet_00000928',
  'tweet_00000929',
  'tweet_00000931',
  'tweet_00000932',
  'tweet_00000933',
  'tweet_00000934',
  'tweet_00000936',
  'tweet_00000938',
  'tweet_00000939',
  'tweet_00000940',
  'tweet_00000941',
  'tweet_00000942',
  'tweet_00000943',
  'tweet_00000944',
  'tweet_00000945',
  'tweet_00000946',
  'tweet_00000947',
  'tweet_00000948',
  'tweet_00000950',
  'tweet_00000951',
  'tweet_00000952',
  'tweet_00000953',
  'tweet_00000954',
  'tweet_00000955',
  'tweet_00000956',
  'tweet_00000957',
  'tweet_00000958',
  'tweet_00000959',
  'tweet_00000961',
  'tweet_00000962',
  'tweet_00000963',
  'tweet_00000966',
  'tweet_00000967',
  'tweet_00000970',
  'tweet_00000971',
  'tweet_00000972',
  'tweet_00000973',
  'tweet_00000974',
  'tweet_00000977',
  'tweet_00000978',
  'tweet_00000979',
  'tweet_00000980',
  'tweet_00000983',
  'tweet_00000984',
  'tweet_00000985',
  'tweet_00000986',
  'tweet_00000988',
  'tweet_00000989',
  'tweet_00000990',
  'tweet_00000992',
  'tweet_00000993',
  'tweet_00000994',
  'tweet_00000995',
  'tweet_00000996',
  'tweet_00000998',
  'tweet_00000999',
  'tweet_00001000',
  'tweet_00001003',
  'tweet_00001004',
  'tweet_00001005',
  'tweet_00001006',
  'tweet_00001007',
  'tweet_00001008',
  'tweet_00001010',
  'tweet_00001011',
  'tweet_00001013',
  'tweet_00001014',
  'tweet_00001015',
  'tweet_00001017',
  'tweet_00001019',
  'tweet_00001020',
  'tweet_00001021',
  'tweet_00001022',
  'tweet_00001023',
  'tweet_00001025',
  'tweet_00001026',
  'tweet_00001028',
  'tweet_00001029',
  'tweet_00001030',
  'tweet_00001031',
  'tweet_00001032',
  'tweet_00001033',
  'tweet_00001034',
  'tweet_00001035',
  'tweet_00001036',
  'tweet_00001037',
  'tweet_00001038',
  'tweet_00001039',
  'tweet_00001040',
  'tweet_00001042',
  'tweet_00001043',
  'tweet_00001044',
  'tweet_00001045',
  'tweet_00001050',
  'tweet_00001051',
  'tweet_00001052',
  'tweet_00001053',
  'tweet_00001054',
  'tweet_00001056',
  'tweet_00001057',
  'tweet_00001058',
  'tweet_00001059',
  'tweet_00001060',
  'tweet_00001061',
  'tweet_00001062',
  'tweet_00001063',
  'tweet_00001064',
  'tweet_00001066',
  'tweet_00001067',
  'tweet_00001068',
  'tweet_00001069',
  'tweet_00001070',
  'tweet_00001071',
  'tweet_00001072',
  'tweet_00001075',
  'tweet_00001076',
  'tweet_00001078',
  'tweet_00001082',
  'tweet_00001083',
  'tweet_00001084',
  'tweet_00001085',
  'tweet_00001086',
  'tweet_00001088',
  'tweet_00001089',
  'tweet_00001091',
  'tweet_00001092',
  'tweet_00001093',
  'tweet_00001094',
  'tweet_00001095',
  'tweet_00001096',
  'tweet_00001097',
  'tweet_00001098',
  'tweet_00001099',
  'tweet_00001100',
  'tweet_00001101',
  'tweet_00001106',
  'tweet_00001107',
  'tweet_00001108',
  'tweet_00001109',
  'tweet_00001110',
  'tweet_00001111',
  'tweet_00001112',
  'tweet_00001113',
  'tweet_00001114',
  'tweet_00001115',
  'tweet_00001116',
  'tweet_00001117',
  'tweet_00001119',
  'tweet_00001120',
  'tweet_00001121',
  'tweet_00001122',
  'tweet_00001123',
  'tweet_00001124',
  'tweet_00001125',
  'tweet_00001126',
  'tweet_00001127',
  'tweet_00001129',
  'tweet_00001130',
  'tweet_00001131',
  'tweet_00001132',
  'tweet_00001133',
  'tweet_00001134',
  'tweet_00001135',
  'tweet_00001136',
  'tweet_00001137',
  'tweet_00001139',
  'tweet_00001141',
  'tweet_00001144',
  'tweet_00001145',
  'tweet_00001146',
  'tweet_00001147',
  'tweet_00001148',
  'tweet_00001150',
  'tweet_00001151',
  'tweet_00001152',
  'tweet_00001153',
  'tweet_00001154',
  'tweet_00001155',
  'tweet_00001156',
  'tweet_00001157',
  'tweet_00001158',
  'tweet_00001159',
  'tweet_00001161',
  'tweet_00001162',
  'tweet_00001163',
  'tweet_00001164',
  'tweet_00001165',
  'tweet_00001166',
  'tweet_00001167',
  'tweet_00001168',
  'tweet_00001169',
  'tweet_00001170',
  'tweet_00001172',
  'tweet_00001173',
  'tweet_00001174',
  'tweet_00001175',
  'tweet_00001176',
  'tweet_00001177',
  'tweet_00001178',
  'tweet_00001179',
  'tweet_00001180',
  'tweet_00001181',
  'tweet_00001183',
  'tweet_00001184',
  'tweet_00001186',
  'tweet_00001187',
  'tweet_00001188',
  'tweet_00001190',
  'tweet_00001191',
  'tweet_00001192',
  'tweet_00001193',
  'tweet_00001194',
  'tweet_00001195',
  'tweet_00001196',
  'tweet_00001197',
  'tweet_00001199',
  'tweet_00001200',
  'tweet_00001201',
  'tweet_00001202',
  'tweet_00001203',
  'tweet_00001205',
  'tweet_00001206',
  'tweet_00001207',
  'tweet_00001208',
  'tweet_00001209',
  'tweet_00001210',
  'tweet_00001211',
  'tweet_00001212',
  'tweet_00001213',
  'tweet_00001214',
  'tweet_00001215',
  'tweet_00001216',
  'tweet_00001217',
  'tweet_00001218',
  'tweet_00001219',
  'tweet_00001222',
  'tweet_00001223',
  'tweet_00001224',
  'tweet_00001225',
  'tweet_00001227',
  'tweet_00001228',
  'tweet_00001231',
  'tweet_00001232',
  'tweet_00001235',
  'tweet_00001237',
  'tweet_00001238',
  'tweet_00001239',
  'tweet_00001240',
  'tweet_00001241',
  'tweet_00001242',
  'tweet_00001243',
  'tweet_00001244',
  'tweet_00001245',
  'tweet_00001246',
  'tweet_00001247',
  'tweet_00001248',
  'tweet_00001249',
  'tweet_00001250',
  'tweet_00001251',
  'tweet_00001253',
  'tweet_00001254',
  'tweet_00001255',
  'tweet_00001257',
  'tweet_00001259',
  'tweet_00001260',
  'tweet_00001261',
  'tweet_00001262',
  'tweet_00001263',
  'tweet_00001265',
  'tweet_00001266',
  'tweet_00001267',
  'tweet_00001269',
  'tweet_00001270',
  'tweet_00001271',
  'tweet_00001272',
  'tweet_00001273',
  'tweet_00001274',
  'tweet_00001277',
  'tweet_00001278',

## Merge verbal and visual scores for CCA

Create the CCA-ready dataset by inner-merging the verbal and visual score DataFrames on `file_id`, keeping only commercials present in both modalities.

In [15]:
cca_df = scores_verbal_df.merge(
    scores_file_ids_visual_df,
    on="file_id",
    how="inner",
)

cca_df

,file_id,image_id,ver1,ver2,ver3,ver4,ver5,ver6,text_id,filename,vis1,vis2,vis3,vis4,vis5,vis6,vis7
0,tweet_00000006,saude202003_n_00001_00000001.jpg,1,1,0,-1,0,0,t000001,saude202003_n_00001_00000001.txt,0,0,0,0,0,0,-2
1,tweet_00000022,saude202003_n_00001_00000002.jpg,-1,3,0,0,0,0,t000002,saude202003_n_00001_00000002.txt,1,0,0,1,0,0,-2
2,tweet_00000051,saude202003_n_00002_00000001.jpg,-1,2,0,-1,-1,0,t000003,saude202003_n_00002_00000001.txt,6,0,0,0,0,0,-6
3,tweet_00000054,saude202003_n_00002_00000002.jpg,1,1,-1,0,0,0,t000004,saude202003_n_00002_00000002.txt,1,0,0,1,0,0,-3
4,tweet_00000073,saude202003_n_00002_00000003.jpg,1,2,0,-1,0,0,t000005,saude202003_n_00002_00000003.txt,19,-1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11844,tweet_00163212,saude202303_n_00207_00000001.jpg,0,1,0,1,0,2,t011865,saude202303_n_00207_00000001.txt,0,0,0,0,0,0,-4
11845,tweet_00163219,saude202303_n_00207_00000002.jpg,0,0,0,0,0,1,t011866,saude202303_n_00207_00000002.txt,3,0,0,0,0,0,-4
11846,tweet_00163225,saude202303_n_00207_00000003.jpg,0,2,0,0,0,0,t011867,saude202303_n_00207_00000003.txt,0,0,0,0,0,-5,0
11847,tweet_00163233,saude202303_n_00207_00000004.png,0,3,0,-1,0,0,t011868,saude202303_n_00207_00000004.txt,0,8,0,4,0,0,19
11848,tweet_00163250,saude202303_n_00207_00000005.jpg,1,0,0,0,0,0,t011869,saude202303_n_00207_00000005.txt,0,0,0,0,0,1,0

In [16]:
cca_df = cca_df.drop(
    columns=[
        "text_id",
        "filename",
    ]
)

cca_df

,file_id,image_id,ver1,ver2,ver3,ver4,ver5,ver6,vis1,vis2,vis3,vis4,vis5,vis6,vis7
0,tweet_00000006,saude202003_n_00001_00000001.jpg,1,1,0,-1,0,0,0,0,0,0,0,0,-2
1,tweet_00000022,saude202003_n_00001_00000002.jpg,-1,3,0,0,0,0,1,0,0,1,0,0,-2
2,tweet_00000051,saude202003_n_00002_00000001.jpg,-1,2,0,-1,-1,0,6,0,0,0,0,0,-6
3,tweet_00000054,saude202003_n_00002_00000002.jpg,1,1,-1,0,0,0,1,0,0,1,0,0,-3
4,tweet_00000073,saude202003_n_00002_00000003.jpg,1,2,0,-1,0,0,19,-1,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11844,tweet_00163212,saude202303_n_00207_00000001.jpg,0,1,0,1,0,2,0,0,0,0,0,0,-4
11845,tweet_00163219,saude202303_n_00207_00000002.jpg,0,0,0,0,0,1,3,0,0,0,0,0,-4
11846,tweet_00163225,saude202303_n_00207_00000003.jpg,0,2,0,0,0,0,0,0,0,0,0,-5,0
11847,tweet_00163233,saude202303_n_00207_00000004.png,0,3,0,-1,0,0,0,8,0,4,0,0,19
11848,tweet_00163250,saude202303_n_00207_00000005.jpg,1,0,0,0,0,0,0,0,0,0,0,1,0

### Save the verbal and visual scores as NDJSON, Excel, and TSV

In [17]:
cca_df.to_json(
    "../cl_st1_ph2_tatiana/corpus/tweets_cca.ndjson",
    orient="records",
    lines=True,
    force_ascii=False
)

cca_df.to_excel(
    "../cl_st1_ph2_tatiana/corpus/tweets_cca.xlsx",
    index=False,
    engine="openpyxl"
)

cca_df.to_csv(
    "../cl_st1_ph2_tatiana/corpus/tweets_cca.tsv",
    sep="\t",
    index=False
)